/**
 * src/core/upload/validation.js
 *
 * File validation utilities.
 * No business logic. No feature-specific knowledge.
 */

'use strict';

const path = require('path');

const MIME_ALIASES = {
    'application/x-pdf': 'application/pdf',
    'application/acrobat': 'application/pdf',
    'applications/vnd.pdf': 'application/pdf',
    'text/pdf': 'application/pdf',
    'image/jpg': 'image/jpeg',
};

// ─── MIME matching ────────────────────────────────────────────────────────────

/**
 * Returns true if `mime` matches any rule in `allowed`.
 * Supports wildcards: 'image/*' matches any 'image/...' type.
 */
function isMimeAllowed(mime, allowed = []) {
    const m = normalizeMime(mime);
    return allowed.some(rule =>
        rule.endsWith('/*')
            ? m.startsWith(rule.slice(0, -1))
            : m === rule.toLowerCase()
    );
}

/**
 * Resolves the effective MIME type of an uploaded file.
 * Falls back to extension sniffing when the declared type is
 * 'application/octet-stream' (common on iOS) or missing.
 */
function resolvedMime(file) {
    const declared = normalizeMime(file?.mimetype);
    if (declared && declared !== 'application/octet-stream') return declared;
    return mimeFromExtension(file?.originalname);
}

function normalizeMime(mime) {
    const normalized = (mime || '').toLowerCase().trim();
    return MIME_ALIASES[normalized] || normalized;
}

function mimeFromExtension(filename = '') {
    const ext = path.extname(filename || '').toLowerCase();
    const map = {
        '.pdf':  'application/pdf',
        '.jpg':  'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.png':  'image/png',
        '.webp': 'image/webp',
        '.gif':  'image/gif',
        '.bmp':  'image/bmp',
        '.heic': 'image/heic',
        '.heif': 'image/heif',
    };
    return map[ext] || '';
}

/**
 * Returns the file extension (lowercase, including dot) for an uploaded file.
 * Falls back to MIME-derived extension when originalname has none.
 */
function fileExtension(file) {
    const ext = path.extname(file?.originalname || '');
    if (ext) return ext.toLowerCase();
    const mime = resolvedMime(file);
    const mimeExtMap = {
        'application/pdf': '.pdf',
        'image/jpeg':      '.jpg',
        'image/png':       '.png',
        'image/webp':      '.webp',
        'image/gif':       '.gif',
        'image/bmp':       '.bmp',
        'image/heic':      '.heic',
        'image/heif':      '.heif',
    };
    return mimeExtMap[mime] || '.bin';
}

// ─── Filename safety ──────────────────────────────────────────────────────────

/**
 * Normalizes the original filename into a safe display/debug value.
 * Upload acceptance must not depend on the raw client-supplied filename,
 * because storage filenames are generated by the system.
 *
 * Returns { ok: true, safeName } for every input.
 */
function validateFilename(originalname) {
    const raw = String(originalname || '');
    const withoutNulls = raw.replace(/\x00/g, '').trim();
    const basename = path.basename(withoutNulls || 'upload');
    const safeName = basename
        .replace(/[<>:"/\\|?*\x00-\x1F]/g, '_')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, 200) || 'upload';

    return { ok: true, safeName };
}

// ─── Size ─────────────────────────────────────────────────────────────────────

function mb(n) { return n * 1024 * 1024; }

function validateSize(sizeBytes, maxMB, label = 'File') {
    if (sizeBytes === 0) return { ok: false, error: `${label}: File is empty (0 bytes).` };
    if (sizeBytes > mb(maxMB)) {
        const actual = (sizeBytes / mb(1)).toFixed(1);
        return { ok: false, error: `${label}: File too large (${actual} MB). Maximum is ${maxMB} MB.` };
    }
    return { ok: true };
}

module.exports = { isMimeAllowed, resolvedMime, fileExtension, validateFilename, validateSize, mb };
